### ISSUE TITLE
CFDropCheckoutPayment.getCfSession()' on a null object reference

### ISSUE THREAD

**Issue by kishanverma26** [cashfree/cashfree-sdk-java#12]
```
 java.lang.NullPointerException: Attempt to invoke virtual method 'com.cashfree.pg.core.api.CFSession com.cashfree.pg.ui.api.CFDropCheckoutPayment.getCfSession()' on a null object reference
        at com.cashfree.pg.ui.m0.a(Unknown Source:5)
        at com.cashfree.pg.ui.hidden.checkout.CashfreeNativeCheckoutActivity.f(Unknown Source:2)
        at com.cashfree.pg.ui.hidden.checkout.CashfreeNativeCheckoutActivity.lambda$kXYgyf2I4miDz2kL6Xaa_5FHRBc(Unknown Source:0)
        at com.cashfree.pg.ui.hidden.checkout.-$$Lambda$CashfreeNativeCheckoutActivity$kXYgyf2I4miDz2kL6Xaa_5FHRBc.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
     
```

Crashing after payment made successfully

**Comment by aabhasr1** [comment]
Greetings,
 this issue is raised in the wrong repo.
 Here is the link to correct repo - https://github.com/cashfree/nextgen-android
 The repo is updated to the latest version v1.0.4 on master.
 Please take a look and if the issue persists then raise a issue in that repo.
 Closing the ticket here
